export const WEAPON_ARCHETYPES = {
  dagger: {
    id: "dagger",
    displayName: "Dagger",
    attackPattern: "daggerSlash",
    damageMultiplier: 0.82,
    rangeMultiplier: 0.72,
    startup: 1,
    active: 9,
    recovery: 5,
    swingArc: 58,
    baseRange: 38,
    baseStats: {
      damage: 8,
      useTime: 15,
      knockback: 2.4,
      range: 38,
      inkCost: 0,
      criticalChance: 0.09,
    },
    hitbox: {
      width: 40,
      height: 30,
      arc: 58,
    },
    animationPreset: {
      pattern: "arcSlash",
      swingArcDegrees: 58,
    },
  },
  sword: {
    id: "sword",
    displayName: "Sword",
    attackPattern: "arcSlash",
    damageMultiplier: 1,
    rangeMultiplier: 1,
    startup: 1,
    active: 7,
    recovery: 6,
    swingArc: 75,
    baseRange: 56,
    baseStats: {
      damage: 12,
      useTime: 16,
      knockback: 3.2,
      range: 56,
      inkCost: 0,
      criticalChance: 0.04,
    },
    hitbox: {
      width: 58,
      height: 38,
      arc: 75,
    },
    animationPreset: {
      pattern: "arcSlash",
      swingArcDegrees: 75,
    },
  },
  spear: {
    id: "spear",
    displayName: "Spear",
    attackPattern: "thrust",
    damageMultiplier: 0.85,
    rangeMultiplier: 1.35,
    startup: 2,
    active: 6,
    recovery: 7,
    thrustDistance: 72,
    baseRange: 86,
    baseStats: {
      damage: 10,
      useTime: 18,
      knockback: 3,
      range: 86,
      inkCost: 0,
      criticalChance: 0.07,
    },
    hitbox: {
      width: 82,
      height: 22,
      arc: 18,
    },
    animationPreset: {
      pattern: "thrust",
      thrustDistance: 72,
    },
  },
  hammer: {
    id: "hammer",
    displayName: "Hammer",
    attackPattern: "heavySmash",
    damageMultiplier: 1.45,
    rangeMultiplier: 0.85,
    startup: 5,
    active: 7,
    recovery: 12,
    impactRadius: 48,
    baseRange: 48,
    baseStats: {
      damage: 17,
      useTime: 28,
      knockback: 7,
      range: 48,
      inkCost: 0,
      criticalChance: 0.03,
    },
    hitbox: {
      width: 64,
      height: 52,
      arc: 95,
    },
    animationPreset: {
      pattern: "heavySmash",
      impactRadius: 48,
    },
  },
  shield: {
    id: "shield",
    displayName: "Shield",
    attackPattern: "guardBash",
    damageMultiplier: 0.65,
    rangeMultiplier: 0.75,
    startup: 2,
    active: 5,
    recovery: 8,
    blockWindow: 8,
    baseRange: 38,
    baseStats: {
      damage: 8,
      useTime: 18,
      knockback: 4.5,
      range: 38,
      inkCost: 0,
      criticalChance: 0.02,
    },
    hitbox: {
      width: 44,
      height: 42,
      arc: 35,
    },
    animationPreset: {
      pattern: "guardBash",
      blockWindow: 8,
    },
  },
  staff: {
    id: "staff",
    displayName: "Staff",
    attackPattern: "arcSlash",
    damageMultiplier: 0.9,
    rangeMultiplier: 1.2,
    startup: 2,
    active: 6,
    recovery: 7,
    swingArc: 85,
    baseRange: 70,
    baseStats: {
      damage: 11,
      useTime: 20,
      knockback: 2.8,
      range: 70,
      inkCost: 2,
      criticalChance: 0.06,
    },
    hitbox: {
      width: 72,
      height: 34,
      arc: 85,
    },
    animationPreset: {
      pattern: "arcSlash",
      swingArcDegrees: 85,
    },
  },
  sketch_sword: {
    id: "sketch_sword",
    displayName: "Sketch Sword",
    attackPattern: "melee_arc",
    baseStats: {
      damage: 12,
      useTime: 16,
      knockback: 3.2,
      range: 52,
      inkCost: 0,
      criticalChance: 0.04,
    },
    hitbox: {
      width: 48,
      height: 28,
      arc: 70,
    },
    visualPreset: {
      heldWidth: 30,
      heldHeight: 14,
      attackWidth: 46,
      attackHeight: 24,
      pivotX: 0.15,
    },
  },
  ink_spear: {
    id: "ink_spear",
    displayName: "Ink Spear",
    attackPattern: "thrust_line",
    baseStats: {
      damage: 11,
      useTime: 20,
      knockback: 3,
      range: 58,
      inkCost: 1,
      criticalChance: 0.07,
    },
    hitbox: {
      width: 64,
      height: 18,
      arc: 28,
    },
    visualPreset: {
      heldWidth: 38,
      heldHeight: 11,
      attackWidth: 66,
      attackHeight: 18,
      pivotX: 0.08,
    },
  },
  charcoal_hammer: {
    id: "charcoal_hammer",
    displayName: "Charcoal Hammer",
    attackPattern: "heavy_slam",
    baseStats: {
      damage: 18,
      useTime: 28,
      knockback: 7,
      range: 34,
      inkCost: 0,
      criticalChance: 0.03,
    },
    hitbox: {
      width: 46,
      height: 38,
      arc: 95,
    },
    visualPreset: {
      heldWidth: 30,
      heldHeight: 22,
      attackWidth: 48,
      attackHeight: 36,
      pivotX: 0.18,
    },
  },
  brush_wave: {
    id: "brush_wave",
    displayName: "Brush Wave",
    attackPattern: "ink_wave",
    baseStats: {
      damage: 10,
      useTime: 24,
      knockback: 3,
      range: 52,
      inkCost: 7,
      criticalChance: 0.04,
    },
    hitbox: {
      width: 58,
      height: 42,
      arc: 110,
    },
    visualPreset: {
      heldWidth: 32,
      heldHeight: 18,
      attackWidth: 58,
      attackHeight: 34,
      pivotX: 0.12,
    },
  },
  paper_boomerang: {
    id: "paper_boomerang",
    displayName: "Paper Boomerang",
    attackPattern: "returning_throw",
    baseStats: {
      damage: 9,
      useTime: 26,
      knockback: 2,
      range: 62,
      inkCost: 2,
      criticalChance: 0.06,
    },
    hitbox: {
      width: 50,
      height: 24,
      arc: 45,
    },
    visualPreset: {
      heldWidth: 26,
      heldHeight: 16,
      attackWidth: 44,
      attackHeight: 24,
      pivotX: 0.5,
    },
  },
  line_whip: {
    id: "line_whip",
    displayName: "Line Whip",
    attackPattern: "whip_chain",
    baseStats: {
      damage: 8,
      useTime: 22,
      knockback: 2,
      range: 54,
      inkCost: 1,
      criticalChance: 0.05,
    },
    hitbox: {
      width: 60,
      height: 24,
      arc: 62,
    },
    visualPreset: {
      heldWidth: 34,
      heldHeight: 10,
      attackWidth: 62,
      attackHeight: 18,
      pivotX: 0.05,
    },
  },
};

export function getWeaponArchetype(id = "sword") {
  const rawId = String(id || "sword");
  const normalizedType = rawId.trim().toLowerCase().replace(/[\s-]+/g, "_");
  const aliasMap = {
    blade: "sword",
    magicstaff: "staff",
    magic_staff: "staff",
    axe: "hammer",
    maul: "hammer",
  };
  const archetypeId = WEAPON_ARCHETYPES[rawId] ? rawId : aliasMap[normalizedType] ?? normalizedType;
  return WEAPON_ARCHETYPES[archetypeId] ?? WEAPON_ARCHETYPES.sword;
}

export function listWeaponArchetypes() {
  return Object.values(WEAPON_ARCHETYPES);
}
